default:
  image: ros:humble

stages:
  - build

build-job:
  stage: build
  script:
    - sudo apt update && sudo apt install -y qtbase5-dev libopencv-dev ros-humble-catch-ros2 ros-humble-cv-bridge
    - mkdir -p ros2_ws/src/mediassist4_ros_tools
    - cp -r resources src test CMakeLists.txt package.xml ros2_ws/src/mediassist4_ros_tools
    - cd ros2_ws
    - source /opt/ros/humble/setup.bash
    - colcon build --packages-select mediassist4_ros_tools
    - source install/setup.bash
    - ros2 run mediassist4_ros_tools tool_tests
    - sudo apt install -y qt6-base-dev
    - colcon build --packages-select mediassist4_ros_tools
    - ros2 run mediassist4_ros_tools tool_tests
