repos:
  - repo: local
    hooks:
      - id: uncrustify
        name: uncrustify
        description: Format files
        entry: uncrustify -c uncrustify.cfg --replace --no-backup
        language: system
        files: \.(cpp|hpp)$
