name: build and test

on:
  workflow_call:
    inputs:
      distro:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  build_and_test:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ inputs.distro }}

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y qt6-base-dev ros-${{ inputs.distro }}-catch-ros2

      - name: Create workspace and copy repo there
        run: mkdir -p ros2_ws/src/ros2_utils_tool && cp -r resources src test CMakeLists.txt package.xml ros2_ws/src/ros2_utils_tool

      - name: Source ROS and build ws
        run: cd ros2_ws && source /opt/ros/${{ inputs.distro }}/setup.bash && colcon build --packages-select ros2_utils_tool

      - name: Source ws and run tests
        run: cd ros2_ws && source install/setup.bash && ros2 run ros2_utils_tool tool_tests
